/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as EntwuerfeRouteImport } from './routes/entwuerfe'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedErgebnisseRouteImport } from './routes/_authenticated/ergebnisse'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppAppIdRouteImport } from './routes/app.$appId'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as EinladungTokenRouteImport } from './routes/einladung.$token'
import { Route as LibraryTokenRouteImport } from './routes/library.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedKontoIndexRouteImport } from './routes/_authenticated/konto.index'
import { Route as AuthenticatedKontoAdminRouteImport } from './routes/_authenticated/konto.admin'
import { Route as AuthenticatedKontoAppsRouteImport } from './routes/_authenticated/konto.apps'
import { Route as AuthenticatedKontoDatenschutzRouteImport } from './routes/_authenticated/konto.datenschutz'
import { Route as AuthenticatedKontoEinstellungenRouteImport } from './routes/_authenticated/konto.einstellungen'
import { Route as AuthenticatedKontoGovernanceRouteImport } from './routes/_authenticated/konto.governance'
import { Route as AuthenticatedKontoKiSchluesselRouteImport } from './routes/_authenticated/konto.ki-schluessel'
import { Route as AuthenticatedKontoMcpRouteImport } from './routes/_authenticated/konto.mcp'
import { Route as AuthenticatedKontoMitgliederRouteImport } from './routes/_authenticated/konto.mitglieder'
import { Route as AuthenticatedKontoOrganisationRouteImport } from './routes/_authenticated/konto.organisation'
import { Route as AuthenticatedKontoSitzungenRouteImport } from './routes/_authenticated/konto.sitzungen'
import { Route as AuthenticatedKontoTeamsRouteImport } from './routes/_authenticated/konto.teams'
import { Route as ApiPublicRunsPurgeRouteImport } from './routes/api/public/runs-purge'
import { Route as EmbedZoneZoneIdRouteImport } from './routes/embed.zone.$zoneId'
import { Route as AuthenticatedKontoNutzerUserIdRouteImport } from './routes/_authenticated/konto.nutzer.$userId'
import { Route as ApiPublicTriggersTriggerIdRouteImport } from './routes/api/public/triggers.$triggerId'
import { Route as ApiPublicAppAppIdMcpRouteImport } from './routes/api/public/app.$appId.mcp'
import { Route as ApiPublicAppAppIdTeamsCardRouteImport } from './routes/api/public/app.$appId.teams-card'
import { Route as ApiPublicAppAppIdTeamsManifestRouteImport } from './routes/api/public/app.$appId.teams-manifest'
import { Route as ApiPublicScopesScopeIdRunRouteImport } from './routes/api/public/scopes.$scopeId.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const EntwuerfeRoute = EntwuerfeRouteImport.update({
  id: '/entwuerfe',
  path: '/entwuerfe',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedErgebnisseRoute = AuthenticatedErgebnisseRouteImport.update({
  id: '/ergebnisse',
  path: '/ergebnisse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdRoute = AppAppIdRouteImport.update({
  id: '/app/$appId',
  path: '/app/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const EinladungTokenRoute = EinladungTokenRouteImport.update({
  id: '/einladung/$token',
  path: '/einladung/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryTokenRoute = LibraryTokenRouteImport.update({
  id: '/library/$token',
  path: '/library/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKontoIndexRoute = AuthenticatedKontoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedKontoRoute,
} as any)
const AuthenticatedKontoAdminRoute = AuthenticatedKontoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedKontoRoute,
} as any)
const AuthenticatedKontoAppsRoute = AuthenticatedKontoAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedKontoRoute,
} as any)
const AuthenticatedKontoDatenschutzRoute =
  AuthenticatedKontoDatenschutzRouteImport.update({
    id: '/datenschutz',
    path: '/datenschutz',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoEinstellungenRoute =
  AuthenticatedKontoEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoGovernanceRoute =
  AuthenticatedKontoGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoKiSchluesselRoute =
  AuthenticatedKontoKiSchluesselRouteImport.update({
    id: '/ki-schluessel',
    path: '/ki-schluessel',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoMcpRoute = AuthenticatedKontoMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedKontoRoute,
} as any)
const AuthenticatedKontoMitgliederRoute =
  AuthenticatedKontoMitgliederRouteImport.update({
    id: '/mitglieder',
    path: '/mitglieder',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoOrganisationRoute =
  AuthenticatedKontoOrganisationRouteImport.update({
    id: '/organisation',
    path: '/organisation',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoSitzungenRoute =
  AuthenticatedKontoSitzungenRouteImport.update({
    id: '/sitzungen',
    path: '/sitzungen',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const AuthenticatedKontoTeamsRoute = AuthenticatedKontoTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedKontoRoute,
} as any)
const ApiPublicRunsPurgeRoute = ApiPublicRunsPurgeRouteImport.update({
  id: '/api/public/runs-purge',
  path: '/api/public/runs-purge',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedZoneZoneIdRoute = EmbedZoneZoneIdRouteImport.update({
  id: '/embed/zone/$zoneId',
  path: '/embed/zone/$zoneId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKontoNutzerUserIdRoute =
  AuthenticatedKontoNutzerUserIdRouteImport.update({
    id: '/nutzer/$userId',
    path: '/nutzer/$userId',
    getParentRoute: () => AuthenticatedKontoRoute,
  } as any)
const ApiPublicTriggersTriggerIdRoute =
  ApiPublicTriggersTriggerIdRouteImport.update({
    id: '/api/public/triggers/$triggerId',
    path: '/api/public/triggers/$triggerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppAppIdMcpRoute = ApiPublicAppAppIdMcpRouteImport.update({
  id: '/api/public/app/$appId/mcp',
  path: '/api/public/app/$appId/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppAppIdTeamsCardRoute =
  ApiPublicAppAppIdTeamsCardRouteImport.update({
    id: '/api/public/app/$appId/teams-card',
    path: '/api/public/app/$appId/teams-card',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppAppIdTeamsManifestRoute =
  ApiPublicAppAppIdTeamsManifestRouteImport.update({
    id: '/api/public/app/$appId/teams-manifest',
    path: '/api/public/app/$appId/teams-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScopesScopeIdRunRoute =
  ApiPublicScopesScopeIdRunRouteImport.update({
    id: '/api/public/scopes/$scopeId/run',
    path: '/api/public/scopes/$scopeId/run',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/entwuerfe': typeof EntwuerfeRoute
  '/impressum': typeof ImpressumRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ergebnisse': typeof AuthenticatedErgebnisseRoute
  '/konto': typeof AuthenticatedKontoRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/$appId': typeof AppAppIdRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/einladung/$token': typeof EinladungTokenRoute
  '/library/$token': typeof LibraryTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/konto/admin': typeof AuthenticatedKontoAdminRoute
  '/konto/apps': typeof AuthenticatedKontoAppsRoute
  '/konto/datenschutz': typeof AuthenticatedKontoDatenschutzRoute
  '/konto/einstellungen': typeof AuthenticatedKontoEinstellungenRoute
  '/konto/governance': typeof AuthenticatedKontoGovernanceRoute
  '/konto/ki-schluessel': typeof AuthenticatedKontoKiSchluesselRoute
  '/konto/mcp': typeof AuthenticatedKontoMcpRoute
  '/konto/mitglieder': typeof AuthenticatedKontoMitgliederRoute
  '/konto/organisation': typeof AuthenticatedKontoOrganisationRoute
  '/konto/sitzungen': typeof AuthenticatedKontoSitzungenRoute
  '/konto/teams': typeof AuthenticatedKontoTeamsRoute
  '/api/public/runs-purge': typeof ApiPublicRunsPurgeRoute
  '/embed/zone/$zoneId': typeof EmbedZoneZoneIdRoute
  '/konto/': typeof AuthenticatedKontoIndexRoute
  '/konto/nutzer/$userId': typeof AuthenticatedKontoNutzerUserIdRoute
  '/api/public/triggers/$triggerId': typeof ApiPublicTriggersTriggerIdRoute
  '/api/public/app/$appId/mcp': typeof ApiPublicAppAppIdMcpRoute
  '/api/public/app/$appId/teams-card': typeof ApiPublicAppAppIdTeamsCardRoute
  '/api/public/app/$appId/teams-manifest': typeof ApiPublicAppAppIdTeamsManifestRoute
  '/api/public/scopes/$scopeId/run': typeof ApiPublicScopesScopeIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/entwuerfe': typeof EntwuerfeRoute
  '/impressum': typeof ImpressumRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ergebnisse': typeof AuthenticatedErgebnisseRoute
  '/api/chat': typeof ApiChatRoute
  '/app/$appId': typeof AppAppIdRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/einladung/$token': typeof EinladungTokenRoute
  '/library/$token': typeof LibraryTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/konto/admin': typeof AuthenticatedKontoAdminRoute
  '/konto/apps': typeof AuthenticatedKontoAppsRoute
  '/konto/datenschutz': typeof AuthenticatedKontoDatenschutzRoute
  '/konto/einstellungen': typeof AuthenticatedKontoEinstellungenRoute
  '/konto/governance': typeof AuthenticatedKontoGovernanceRoute
  '/konto/ki-schluessel': typeof AuthenticatedKontoKiSchluesselRoute
  '/konto/mcp': typeof AuthenticatedKontoMcpRoute
  '/konto/mitglieder': typeof AuthenticatedKontoMitgliederRoute
  '/konto/organisation': typeof AuthenticatedKontoOrganisationRoute
  '/konto/sitzungen': typeof AuthenticatedKontoSitzungenRoute
  '/konto/teams': typeof AuthenticatedKontoTeamsRoute
  '/api/public/runs-purge': typeof ApiPublicRunsPurgeRoute
  '/embed/zone/$zoneId': typeof EmbedZoneZoneIdRoute
  '/konto': typeof AuthenticatedKontoIndexRoute
  '/konto/nutzer/$userId': typeof AuthenticatedKontoNutzerUserIdRoute
  '/api/public/triggers/$triggerId': typeof ApiPublicTriggersTriggerIdRoute
  '/api/public/app/$appId/mcp': typeof ApiPublicAppAppIdMcpRoute
  '/api/public/app/$appId/teams-card': typeof ApiPublicAppAppIdTeamsCardRoute
  '/api/public/app/$appId/teams-manifest': typeof ApiPublicAppAppIdTeamsManifestRoute
  '/api/public/scopes/$scopeId/run': typeof ApiPublicScopesScopeIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/entwuerfe': typeof EntwuerfeRoute
  '/impressum': typeof ImpressumRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ergebnisse': typeof AuthenticatedErgebnisseRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/$appId': typeof AppAppIdRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/einladung/$token': typeof EinladungTokenRoute
  '/library/$token': typeof LibraryTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/konto/admin': typeof AuthenticatedKontoAdminRoute
  '/_authenticated/konto/apps': typeof AuthenticatedKontoAppsRoute
  '/_authenticated/konto/datenschutz': typeof AuthenticatedKontoDatenschutzRoute
  '/_authenticated/konto/einstellungen': typeof AuthenticatedKontoEinstellungenRoute
  '/_authenticated/konto/governance': typeof AuthenticatedKontoGovernanceRoute
  '/_authenticated/konto/ki-schluessel': typeof AuthenticatedKontoKiSchluesselRoute
  '/_authenticated/konto/mcp': typeof AuthenticatedKontoMcpRoute
  '/_authenticated/konto/mitglieder': typeof AuthenticatedKontoMitgliederRoute
  '/_authenticated/konto/organisation': typeof AuthenticatedKontoOrganisationRoute
  '/_authenticated/konto/sitzungen': typeof AuthenticatedKontoSitzungenRoute
  '/_authenticated/konto/teams': typeof AuthenticatedKontoTeamsRoute
  '/api/public/runs-purge': typeof ApiPublicRunsPurgeRoute
  '/embed/zone/$zoneId': typeof EmbedZoneZoneIdRoute
  '/_authenticated/konto/': typeof AuthenticatedKontoIndexRoute
  '/_authenticated/konto/nutzer/$userId': typeof AuthenticatedKontoNutzerUserIdRoute
  '/api/public/triggers/$triggerId': typeof ApiPublicTriggersTriggerIdRoute
  '/api/public/app/$appId/mcp': typeof ApiPublicAppAppIdMcpRoute
  '/api/public/app/$appId/teams-card': typeof ApiPublicAppAppIdTeamsCardRoute
  '/api/public/app/$appId/teams-manifest': typeof ApiPublicAppAppIdTeamsManifestRoute
  '/api/public/scopes/$scopeId/run': typeof ApiPublicScopesScopeIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/auth'
    | '/datenschutz'
    | '/entwuerfe'
    | '/impressum'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/ergebnisse'
    | '/konto'
    | '/api/chat'
    | '/app/$appId'
    | '/board/$boardId'
    | '/einladung/$token'
    | '/library/$token'
    | '/share/$token'
    | '/.lovable/oauth/consent'
    | '/konto/admin'
    | '/konto/apps'
    | '/konto/datenschutz'
    | '/konto/einstellungen'
    | '/konto/governance'
    | '/konto/ki-schluessel'
    | '/konto/mcp'
    | '/konto/mitglieder'
    | '/konto/organisation'
    | '/konto/sitzungen'
    | '/konto/teams'
    | '/api/public/runs-purge'
    | '/embed/zone/$zoneId'
    | '/konto/'
    | '/konto/nutzer/$userId'
    | '/api/public/triggers/$triggerId'
    | '/api/public/app/$appId/mcp'
    | '/api/public/app/$appId/teams-card'
    | '/api/public/app/$appId/teams-manifest'
    | '/api/public/scopes/$scopeId/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/auth'
    | '/datenschutz'
    | '/entwuerfe'
    | '/impressum'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/ergebnisse'
    | '/api/chat'
    | '/app/$appId'
    | '/board/$boardId'
    | '/einladung/$token'
    | '/library/$token'
    | '/share/$token'
    | '/.lovable/oauth/consent'
    | '/konto/admin'
    | '/konto/apps'
    | '/konto/datenschutz'
    | '/konto/einstellungen'
    | '/konto/governance'
    | '/konto/ki-schluessel'
    | '/konto/mcp'
    | '/konto/mitglieder'
    | '/konto/organisation'
    | '/konto/sitzungen'
    | '/konto/teams'
    | '/api/public/runs-purge'
    | '/embed/zone/$zoneId'
    | '/konto'
    | '/konto/nutzer/$userId'
    | '/api/public/triggers/$triggerId'
    | '/api/public/app/$appId/mcp'
    | '/api/public/app/$appId/teams-card'
    | '/api/public/app/$appId/teams-manifest'
    | '/api/public/scopes/$scopeId/run'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/auth'
    | '/datenschutz'
    | '/entwuerfe'
    | '/impressum'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ergebnisse'
    | '/_authenticated/konto'
    | '/api/chat'
    | '/app/$appId'
    | '/board/$boardId'
    | '/einladung/$token'
    | '/library/$token'
    | '/share/$token'
    | '/.lovable/oauth/consent'
    | '/_authenticated/konto/admin'
    | '/_authenticated/konto/apps'
    | '/_authenticated/konto/datenschutz'
    | '/_authenticated/konto/einstellungen'
    | '/_authenticated/konto/governance'
    | '/_authenticated/konto/ki-schluessel'
    | '/_authenticated/konto/mcp'
    | '/_authenticated/konto/mitglieder'
    | '/_authenticated/konto/organisation'
    | '/_authenticated/konto/sitzungen'
    | '/_authenticated/konto/teams'
    | '/api/public/runs-purge'
    | '/embed/zone/$zoneId'
    | '/_authenticated/konto/'
    | '/_authenticated/konto/nutzer/$userId'
    | '/api/public/triggers/$triggerId'
    | '/api/public/app/$appId/mcp'
    | '/api/public/app/$appId/teams-card'
    | '/api/public/app/$appId/teams-manifest'
    | '/api/public/scopes/$scopeId/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EntwuerfeRoute: typeof EntwuerfeRoute
  ImpressumRoute: typeof ImpressumRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  AppAppIdRoute: typeof AppAppIdRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  EinladungTokenRoute: typeof EinladungTokenRoute
  LibraryTokenRoute: typeof LibraryTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicRunsPurgeRoute: typeof ApiPublicRunsPurgeRoute
  EmbedZoneZoneIdRoute: typeof EmbedZoneZoneIdRoute
  ApiPublicTriggersTriggerIdRoute: typeof ApiPublicTriggersTriggerIdRoute
  ApiPublicAppAppIdMcpRoute: typeof ApiPublicAppAppIdMcpRoute
  ApiPublicAppAppIdTeamsCardRoute: typeof ApiPublicAppAppIdTeamsCardRoute
  ApiPublicAppAppIdTeamsManifestRoute: typeof ApiPublicAppAppIdTeamsManifestRoute
  ApiPublicScopesScopeIdRunRoute: typeof ApiPublicScopesScopeIdRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entwuerfe': {
      id: '/entwuerfe'
      path: '/entwuerfe'
      fullPath: '/entwuerfe'
      preLoaderRoute: typeof EntwuerfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ergebnisse': {
      id: '/_authenticated/ergebnisse'
      path: '/ergebnisse'
      fullPath: '/ergebnisse'
      preLoaderRoute: typeof AuthenticatedErgebnisseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId': {
      id: '/app/$appId'
      path: '/app/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof AppAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einladung/$token': {
      id: '/einladung/$token'
      path: '/einladung/$token'
      fullPath: '/einladung/$token'
      preLoaderRoute: typeof EinladungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$token': {
      id: '/library/$token'
      path: '/library/$token'
      fullPath: '/library/$token'
      preLoaderRoute: typeof LibraryTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/konto/': {
      id: '/_authenticated/konto/'
      path: '/'
      fullPath: '/konto/'
      preLoaderRoute: typeof AuthenticatedKontoIndexRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/admin': {
      id: '/_authenticated/konto/admin'
      path: '/admin'
      fullPath: '/konto/admin'
      preLoaderRoute: typeof AuthenticatedKontoAdminRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/apps': {
      id: '/_authenticated/konto/apps'
      path: '/apps'
      fullPath: '/konto/apps'
      preLoaderRoute: typeof AuthenticatedKontoAppsRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/datenschutz': {
      id: '/_authenticated/konto/datenschutz'
      path: '/datenschutz'
      fullPath: '/konto/datenschutz'
      preLoaderRoute: typeof AuthenticatedKontoDatenschutzRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/einstellungen': {
      id: '/_authenticated/konto/einstellungen'
      path: '/einstellungen'
      fullPath: '/konto/einstellungen'
      preLoaderRoute: typeof AuthenticatedKontoEinstellungenRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/governance': {
      id: '/_authenticated/konto/governance'
      path: '/governance'
      fullPath: '/konto/governance'
      preLoaderRoute: typeof AuthenticatedKontoGovernanceRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/ki-schluessel': {
      id: '/_authenticated/konto/ki-schluessel'
      path: '/ki-schluessel'
      fullPath: '/konto/ki-schluessel'
      preLoaderRoute: typeof AuthenticatedKontoKiSchluesselRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/mcp': {
      id: '/_authenticated/konto/mcp'
      path: '/mcp'
      fullPath: '/konto/mcp'
      preLoaderRoute: typeof AuthenticatedKontoMcpRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/mitglieder': {
      id: '/_authenticated/konto/mitglieder'
      path: '/mitglieder'
      fullPath: '/konto/mitglieder'
      preLoaderRoute: typeof AuthenticatedKontoMitgliederRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/organisation': {
      id: '/_authenticated/konto/organisation'
      path: '/organisation'
      fullPath: '/konto/organisation'
      preLoaderRoute: typeof AuthenticatedKontoOrganisationRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/sitzungen': {
      id: '/_authenticated/konto/sitzungen'
      path: '/sitzungen'
      fullPath: '/konto/sitzungen'
      preLoaderRoute: typeof AuthenticatedKontoSitzungenRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/_authenticated/konto/teams': {
      id: '/_authenticated/konto/teams'
      path: '/teams'
      fullPath: '/konto/teams'
      preLoaderRoute: typeof AuthenticatedKontoTeamsRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/api/public/runs-purge': {
      id: '/api/public/runs-purge'
      path: '/api/public/runs-purge'
      fullPath: '/api/public/runs-purge'
      preLoaderRoute: typeof ApiPublicRunsPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/zone/$zoneId': {
      id: '/embed/zone/$zoneId'
      path: '/embed/zone/$zoneId'
      fullPath: '/embed/zone/$zoneId'
      preLoaderRoute: typeof EmbedZoneZoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/konto/nutzer/$userId': {
      id: '/_authenticated/konto/nutzer/$userId'
      path: '/nutzer/$userId'
      fullPath: '/konto/nutzer/$userId'
      preLoaderRoute: typeof AuthenticatedKontoNutzerUserIdRouteImport
      parentRoute: typeof AuthenticatedKontoRoute
    }
    '/api/public/triggers/$triggerId': {
      id: '/api/public/triggers/$triggerId'
      path: '/api/public/triggers/$triggerId'
      fullPath: '/api/public/triggers/$triggerId'
      preLoaderRoute: typeof ApiPublicTriggersTriggerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app/$appId/mcp': {
      id: '/api/public/app/$appId/mcp'
      path: '/api/public/app/$appId/mcp'
      fullPath: '/api/public/app/$appId/mcp'
      preLoaderRoute: typeof ApiPublicAppAppIdMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app/$appId/teams-card': {
      id: '/api/public/app/$appId/teams-card'
      path: '/api/public/app/$appId/teams-card'
      fullPath: '/api/public/app/$appId/teams-card'
      preLoaderRoute: typeof ApiPublicAppAppIdTeamsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app/$appId/teams-manifest': {
      id: '/api/public/app/$appId/teams-manifest'
      path: '/api/public/app/$appId/teams-manifest'
      fullPath: '/api/public/app/$appId/teams-manifest'
      preLoaderRoute: typeof ApiPublicAppAppIdTeamsManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scopes/$scopeId/run': {
      id: '/api/public/scopes/$scopeId/run'
      path: '/api/public/scopes/$scopeId/run'
      fullPath: '/api/public/scopes/$scopeId/run'
      preLoaderRoute: typeof ApiPublicScopesScopeIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedKontoRouteChildren {
  AuthenticatedKontoAdminRoute: typeof AuthenticatedKontoAdminRoute
  AuthenticatedKontoAppsRoute: typeof AuthenticatedKontoAppsRoute
  AuthenticatedKontoDatenschutzRoute: typeof AuthenticatedKontoDatenschutzRoute
  AuthenticatedKontoEinstellungenRoute: typeof AuthenticatedKontoEinstellungenRoute
  AuthenticatedKontoGovernanceRoute: typeof AuthenticatedKontoGovernanceRoute
  AuthenticatedKontoKiSchluesselRoute: typeof AuthenticatedKontoKiSchluesselRoute
  AuthenticatedKontoMcpRoute: typeof AuthenticatedKontoMcpRoute
  AuthenticatedKontoMitgliederRoute: typeof AuthenticatedKontoMitgliederRoute
  AuthenticatedKontoOrganisationRoute: typeof AuthenticatedKontoOrganisationRoute
  AuthenticatedKontoSitzungenRoute: typeof AuthenticatedKontoSitzungenRoute
  AuthenticatedKontoTeamsRoute: typeof AuthenticatedKontoTeamsRoute
  AuthenticatedKontoIndexRoute: typeof AuthenticatedKontoIndexRoute
  AuthenticatedKontoNutzerUserIdRoute: typeof AuthenticatedKontoNutzerUserIdRoute
}

const AuthenticatedKontoRouteChildren: AuthenticatedKontoRouteChildren = {
  AuthenticatedKontoAdminRoute: AuthenticatedKontoAdminRoute,
  AuthenticatedKontoAppsRoute: AuthenticatedKontoAppsRoute,
  AuthenticatedKontoDatenschutzRoute: AuthenticatedKontoDatenschutzRoute,
  AuthenticatedKontoEinstellungenRoute: AuthenticatedKontoEinstellungenRoute,
  AuthenticatedKontoGovernanceRoute: AuthenticatedKontoGovernanceRoute,
  AuthenticatedKontoKiSchluesselRoute: AuthenticatedKontoKiSchluesselRoute,
  AuthenticatedKontoMcpRoute: AuthenticatedKontoMcpRoute,
  AuthenticatedKontoMitgliederRoute: AuthenticatedKontoMitgliederRoute,
  AuthenticatedKontoOrganisationRoute: AuthenticatedKontoOrganisationRoute,
  AuthenticatedKontoSitzungenRoute: AuthenticatedKontoSitzungenRoute,
  AuthenticatedKontoTeamsRoute: AuthenticatedKontoTeamsRoute,
  AuthenticatedKontoIndexRoute: AuthenticatedKontoIndexRoute,
  AuthenticatedKontoNutzerUserIdRoute: AuthenticatedKontoNutzerUserIdRoute,
}

const AuthenticatedKontoRouteWithChildren =
  AuthenticatedKontoRoute._addFileChildren(AuthenticatedKontoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErgebnisseRoute: typeof AuthenticatedErgebnisseRoute
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErgebnisseRoute: AuthenticatedErgebnisseRoute,
  AuthenticatedKontoRoute: AuthenticatedKontoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  EntwuerfeRoute: EntwuerfeRoute,
  ImpressumRoute: ImpressumRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  AppAppIdRoute: AppAppIdRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  EinladungTokenRoute: EinladungTokenRoute,
  LibraryTokenRoute: LibraryTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicRunsPurgeRoute: ApiPublicRunsPurgeRoute,
  EmbedZoneZoneIdRoute: EmbedZoneZoneIdRoute,
  ApiPublicTriggersTriggerIdRoute: ApiPublicTriggersTriggerIdRoute,
  ApiPublicAppAppIdMcpRoute: ApiPublicAppAppIdMcpRoute,
  ApiPublicAppAppIdTeamsCardRoute: ApiPublicAppAppIdTeamsCardRoute,
  ApiPublicAppAppIdTeamsManifestRoute: ApiPublicAppAppIdTeamsManifestRoute,
  ApiPublicScopesScopeIdRunRoute: ApiPublicScopesScopeIdRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
